### ISSUE TITLE
Tema do projeto

### ISSUE THREAD

**Issue by brunna-martins** [brunna-martins/ProjetoX#1]
## Descrição: 
Agora que foi decidido que faremos um projeto, é necessário definir o tema.

## Tarefas:
Checklist de tarefas a serem feitas.
- [x] Reunir temas possíveis.
- [x] Escolher dentre os temas apresentados qual será o tema do projeto.

**Comment by pkbceira03** [comment]
Dei uma pesquisada e tive algumas ideias:

-E-commerce;
-Todo List bem comleto;
-Site institucional;
-Clone de um site que já existe;

**Comment by brunna-martins** [comment]
O tema do projeto é To-do List (tema escolhido dia 26/04/2023).
